<h1>ML Zoomcamp HW1<h1>

In [1]:
#import libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

<b> Q1) Version of Pandas </b>

In [2]:
#Q1) What's the version of Pandas that you installed?
pd.__version__

'1.5.3'

In [3]:
#read the data
df1 = pd.read_csv('laptops.csv')
df1.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

<b> Q2) Records count</b>

In [4]:
#Q2) How many records are in the dataset?
df1.shape
#there are 2160 records

(2160, 12)

<b> Q3) Laptop Brands </b>

In [5]:
df1['Brand'].value_counts()

Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Primux                8
Deep Gaming           8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: Brand, dtype: int64

In [6]:
#Q3) How many laptop brands are presented in the dataset?
df1['Brand'].value_counts().shape

#There are 27 brands.

(27,)

<b> Q4) Missing Values </b>

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [18]:
#Q4) How many columns in the dataset have missing values?
df1.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [19]:
df1.isnull().any().sum()
# 3 columns have missing values

3

<b> Q5) Maximum Final Price </b>

In [20]:
#Q5) What's the maximum final price of Dell notebooks in the dataset?
df1[df1['Brand']=='Dell']['Final Price'].max()

3936.0

<b> Q6) Median Value of Screen  </b>

In [21]:
#Q6.1)Did the median change?
df1_median = df1['Screen'].median()
print(df1_median)

15.6


In [22]:
#Q6.2) Most Frequent Value
df1_mode = df1['Screen'].mode()
print(df1_mode)

0    15.6
Name: Screen, dtype: float64


In [23]:
#Q6.3) Replace Null with Most Frequent Value
df1['Screen'].fillna(df1_mode)
df1['Screen']

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [24]:
#Q6.4) Again caluclate the median
df1_median1 = df1['Screen'].median()
print(df1_median1)

#median didn't change

15.6


<b> Q7) Sum of weights </b>

In [25]:
#Q7.1) Select all the "Innjoo" laptops from the dataset.
df2 = df1[df1['Brand']=='Innjoo']
df2

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [26]:
#Q7.2) Select only columns RAM, Storage, Screen.
df3  = df2.iloc[:,[5,6,9]]
df3

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [27]:
#Q7.3) Get the underlying NumPy array. Let's call it X
X = df3.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [28]:
#transpose of X
XT = X.T
XT

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [29]:
#Q7.4) Compute matrix-matrix multiplication between the transpose of X and X.
XTX = np.dot(XT,X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [30]:
#Q7.5) Compute the inverse of XTX
XTXI = np.linalg.inv(XTX)
XTXI

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [31]:
#Q7.6) Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [32]:
#Q7.7) Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
result= np.dot(XTXI,XT)
w=np.dot(result,y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [33]:
#Q7.8) What's the sum of all the elements of the result?
sum_of_elements= w.sum() 
sum_of_elements

91.29988062995815